// Minimal Turkish text fixture covering the keys the components under test
// actually read from `t`. Mirrors the shape of App.jsx's `texts.tr` object.
export const t = {
  title: 'DatHex',
  subtitle: 'Gelişmiş Windows Paket ve Sistem Yöneticisi',
  totalUpdates: 'Toplam Güncelleme',
  selected: 'Seçilen',
  checkUpdates: 'Güncellemeleri Kontrol Et',
  upgradeSelected: 'Seçilenleri Güncelle',
  upgradeAll: 'Tümünü Güncelle',
  cancel: 'İptal Et',
  appName: 'Uygulama Adı',
  id: 'Kimlik (ID)',
  currentVer: 'Mevcut Sürüm',
  newVer: 'Yeni Sürüm',
  noUpdates: 'Güncellenebilir uygulama bulunamadı.',
  serverError: 'Sunucuya bağlanılamadı.',
  menuUpgrades: 'Güncellemeler',
  menuStore: 'Uygulama Mağazası',
  menuInstalled: 'Yüklü Uygulamalar',
  menuBackup: 'Yedekle & Geri Yükle',
  searchPlaceholder: 'Uygulama ara (örn. chrome, vscode)',
  search: 'Ara',
  noResults: 'Sonuç bulunamadı.',
  source: 'Kaynak',
  action: 'İşlem',
  install: 'Yükle',
  confirmUninstall: 'Bu uygulamayı kaldırmak istediğinize emin misiniz?',
  backupDesc: 'Yedekleme açıklaması.',
  exportBtn: 'Yedeği Dışa Aktar',
};
